#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Mappy.Resource", IsApplication=true)]

namespace Mappy
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Mappy.Common.Android.Resource.String.library_name = Mappy.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int atm_medium = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int atm_micro = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int atm_small = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int branch_medium = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int branch_micro = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int branch_small = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int BankEntityOptions = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int CancelButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int OkButton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int OptionsButton = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int SelectAtm = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int SelectBranch = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int SelectPartnerAtms = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int map = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int zoomLevel = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BankEntityTypeSelection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MapLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
